### YamlMime:ManagedReference

apiRules:
- include:
    uidRegex: ^Luny
    type: Namespace
- include:
    uidRegex: ^LunyScript
    type: Namespace
- exclude:
    uidRegex: ^UnityEngine\..*
- exclude:
    uidRegex: ^UnityEditor\..*
- exclude:
    uidRegex: ^Unity\..*
- exclude:
    uidRegex: ^System\.Object
    type: Type
