### YamlMime:ManagedReference

apiRules:
- include:
    uidRegex: ^Luny
    type: Namespace
- include:
    uidRegex: ^LunyScript
    type: Namespace
- exclude:
    uidRegex: ^Unity
    type: Namespace
- exclude:
    uidRegex: ^LunyScript.SmokeTests
    type: Namespace
- exclude:
    uidRegex: .*
    type: Namespace
